# .github/workflows/app.yaml
name: AWS Test Suite With Pytest
on: push

env:
  AWS_REGION : "us-east-1"   
permissions:
      id-token: write 
      contents: read  

jobs:
  AWSDeploymentTesting:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::357171621133:role/github-oidc-role
          role-session-name: samplerolesession
          aws-region: 'us-east-1'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install required python modules
        run: |
          python -m pip install --upgrade boto3 moto pytest pytest-github-report pytest-cov coverage pre-commit

      - name: Run AWS test suite
        working-directory: ./AWSTestExecutions
        run: |
          pytest  --github-report -v --cov=AWSTestCases --cov-report xml:coverage.xml
          pwd

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Publish code coverage results
        uses: 5monkeys/cobertura-action@master
        with:
          path: ${{ github.workspace }}/AWSTestExecutions/coverage.xml
          minimum_coverage: 75




